spring.application.name=simple_timetable_generator

  spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

timefold.solver.termination.spent-limit=180s